version: '3.8'

services:

  #PHP Service
  app:
    container_name: "app-suppermarket-server"
    build:
      context: "./.docker/app/"
      dockerfile: Dockerfile
    restart: "no"
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html"
    depends_on:
      - mysql

  #Nginx Service
  webserver:
    container_name: "webserver-suppermarket-server"
    image: "nginx"
    restart: "no" 
    ports:
      # - "${APP_PORT}:80"
      - "80:80"
      - "6001:6001"
    volumes:
      - "./:/var/www/html"
      - "./.docker/server/nginx.conf:/etc/nginx/conf.d/default.conf"

  # DB UI management service
  myadmin:
    container_name: "myadmin-suppermarket-server"
    image: "phpmyadmin:latest"
    restart: "no"
    ports:
      # - ${ADMINER_PORT}:8080
      - "85:80"
    environment:
      - "UPLOAD_LIMIT=1G"
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=mysql"
    depends_on:
      - "mysql"

  #MySQL Service
  mysql:
    container_name: "mysql-suppermarket-server"
    image: "mysql:8.0"
    restart: "no"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/data/:/var/lib/mysql/"
