name: Testing process
on:
  pull_request:
    types: [opened, closed]
    branches: [test]

jobs:
  testing:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 my_app/bootstrap/cache
      - name: Move to application
        run: cd my_app
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit --testdox